# Generated by Django 4.0.4 on 2026-01-03 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redbus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bus',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
